quizzes/models.py
import enum
from typing import Dict

import flask_sqlalchemy
import flask_user

db = flask_sqlalchemy.SQLAlchemy()


class QuizDifficulty(enum.Enum):
    EASY = 1
    MEDIUM = 2
    HARD = 3


POINTS_MULTIPLIER = {
    QuizDifficulty.EASY: 1,
    QuizDifficulty.MEDIUM: 2,
    QuizDifficulty.HARD: 4,
}


class User(db.Model, flask_user.UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer(), primary_key=True)
    active = db.Column("is_active", db.Boolean(), nullable=False, server_default="1")
    username = db.Column(db.String(255), nullable=False, unique=True)
    password = db.Column(db.String(255), nullable=False, server_default="")
    first_name = db.Column(db.String(100), nullable=False, server_default="")
    last_name = db.Column(db.String(100), nullable=False, server_default="")
    quiz_results = db.relationship("QuizResult", back_populates="user")


class QuizResult(db.Model):
    __tablename__ = "quiz_results"
    id = db.Column(db.Integer(), primary_key=True)
    user_id = db.Column(db.Integer(), db.ForeignKey("users.id"))
    user = db.relationship("User", back_populates="quiz_results")
    quiz_id = db.Column(db.Integer(), db.ForeignKey("quiz.id"))
    quiz = db.relationship("Quiz", back_populates="quiz_result")
    points = db.Column(db.Integer())


class QuizQuestion(db.Model):
    __tablename__ = "quiz_question"
    id = db.Column(db.Integer(), primary_key=True)
    quiz_id = db.Column(db.Integer(), db.ForeignKey("quiz.id"))
    quiz = db.relationship("Quiz", back_populates="quiz_questions")
    question = db.Column(db.String())
    correct_answer = db.Column(db.String())
    incorrect_answers = db.Column(db.JSON())


class Quiz(db.Model):
    __tablename = "quiz"
    id = db.Column(db.Integer(), primary_key=True)
    difficulty = db.Column(db.Enum(QuizDifficulty))
    quiz_result = db.relationship("QuizResult", back_populates="quiz")
    quiz_questions = db.relationship("QuizQuestion", back_populates="quiz")


def calculate_points(quiz: Quiz, answers: Dict) -> int:
    if len(quiz.quiz_questions) != len(answers):
        raise ValueError("Inconsistent questions and answers.")

    quiz.quiz_questions.sort(key=lambda q: q.id)

    points = 0
    for question, answer in zip(quiz.quiz_questions, answers.values()):
        if answer == question.correct_answer:
            points += POINTS_MULTIPLIER[quiz.difficulty]
    return points

quizzes/forms.py
import html
from typing import Type

import wtforms

from quizzes import models


def quiz_form_factory(quiz_taken: models.Quiz) -> Type[wtforms.Form]:
    quiz_taken.quiz_questions.sort(key=lambda q: q.id)
    return type(
        "QuizForm",
        (wtforms.Form,),
        {
            f"question_{i}": wtforms.RadioField(
                html.unescape(q.question), choices=q.incorrect_answers + [q.correct_answer]
            )
            for i, q in enumerate(quiz_taken.quiz_questions, start=1)
        },
    )

quizzes/app.py
import flask
import flask_user
from wtforms import validators


class AppConfig:
    SECRET_KEY = "replace-me"

    SQLALCHEMY_DATABASE_URI = "sqlite:///quizzes.db"  # In Memory
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    USER_APP_NAME = "Quizzes"
    USER_ENABLE_EMAIL = False
    USER_ENABLE_USERNAME = True


class UserManager(flask_user.UserManager):
    def password_validator(self, form, field):
        password_length = len(field.data)
        if not password_length:
            raise validators.ValidationError("The password is too short.")


def bind_models(app: flask.Flask):
    from quizzes import models

    models.db.init_app(app)

    UserManager(app, models.db, models.User)


def prepare_database():
    from quizzes import models

    models.db.create_all()


def bind_views(app: flask.Flask):
    from quizzes import views

    app.register_blueprint(views.blueprint)


def create_app():
    app = flask.Flask(__name__)
    app.config.from_object(AppConfig())
    bind_models(app)
    bind_views(app)
    app.before_first_request(prepare_database)
    return app

quizzes/views.py
import uuid

import flask
from flask import blueprints, templating, helpers
import flask_user
import flask_login
import requests
from sqlalchemy.orm import exc as orm_exceptions

from quizzes import models, forms

blueprint = blueprints.Blueprint("quizzes", __name__)


@blueprint.route("/")
def index():
    return templating.render_template("index.html")


@blueprint.route("/quiz")
@flask_user.login_required
def choose_quiz_difficulty():
    return templating.render_template("choose_quiz_difficulty.html")


@blueprint.route("/quiz/prepare/<difficulty>")
@flask_user.login_required
def prepare_quiz(difficulty: str):
    api_response = requests.get(f"https://opentdb.com/api.php?amount=10&difficulty={difficulty}")
    questions = api_response.json()["results"]

    quiz = models.Quiz(difficulty=models.QuizDifficulty[difficulty.upper()])
    models.db.session.add(quiz)
    for q in questions:
        quiz.quiz_questions.append(
            models.QuizQuestion(
                question=q["question"],
                correct_answer=q["correct_answer"],
                incorrect_answers=q["incorrect_answers"],
            )
        )
    models.db.session.commit()

    return flask.redirect(helpers.url_for("quizzes.take_quiz", quiz_id=quiz.id))


@blueprint.route("/quiz/take/<quiz_id>", methods=["GET", "POST"])
@flask_user.login_required
def take_quiz(quiz_id: int):
    try:
        quiz = models.db.session.query(models.Quiz).filter(models.Quiz.id == quiz_id).one()
    except orm_exceptions.NoResultFound:
        return flask.redirect(helpers.url_for("quizzes.choose_quiz_difficulty"))

    Form = forms.quiz_form_factory(quiz)
    if flask.request.method == "GET":
        return templating.render_template("take_quiz.html", form=Form())
    else:
        form = Form(flask.request.form)
        if form.validate():
            points = models.calculate_points(quiz, flask.request.form)
            models.db.session.add(models.QuizResult(user=flask_login.current_user, quiz=quiz, points=points))
            models.db.session.commit()
            return flask.redirect(helpers.url_for("quizzes.ranking"))
        return templating.render_template("take_quiz.html", form=form)


@blueprint.route("/ranking")
def ranking():
    quiz_results = models.db.session.query(models.QuizResult).order_by(models.QuizResult.points.desc())
    return templating.render_template("ranking.html", ranking=quiz_results)


@blueprint.route("/ranking.json")
def ranking_json():
    quiz_results = models.db.session.query(models.QuizResult).order_by(models.QuizResult.points.desc())
    return {
        "ranking": [
            {
                "user": {
                    "username": r.user.username,
                },
                "quiz": {
                    "id": r.quiz.id,
                },
                "points": r.points,
            }
            for r in quiz_results
        ]
    }

quizzes/templates/choose_quiz_difficulty.html
{% extends 'flask_user_layout.html' %}

{% block content %}
  <h1>Choose quiz difficulty</h1>
  <ul>
    <li><a href="{{ url_for('quizzes.prepare_quiz', difficulty='easy') }}">Easy</a></li>
    <li><a href="{{ url_for('quizzes.prepare_quiz', difficulty='medium') }}">Medium</a></li>
    <li><a href="{{ url_for('quizzes.prepare_quiz', difficulty='hard') }}">Hard</a></li>
  </ul>
{% endblock %}

quizzes/templates/index.html
{% extends 'flask_user_layout.html' %}

{% block content %}
  <h1>Welcome to this project!</h1>
  <ul>
    <li>Registration is under <pre>{{ url_for('user.register') }}</pre></li>
    <li>Authentication is under <pre>{{ url_for('user.login') }}</pre></li>
    <li>Sign out is under <pre>{{ url_for('user.logout') }}</pre></li>
    <li>Start quiz under <pre>{{ url_for('quizzes.choose_quiz_difficulty') }}</pre></li>
    <li>See ranking under <pre>{{ url_for('quizzes.ranking') }}</pre></li>
    <li>API ranking under <pre>{{ url_for('quizzes.ranking_json') }}</pre></li>
  </ul>
{% endblock %}

quizzes/templates/ranking.html
{% extends 'flask_user_layout.html' %}

{% block content %}
  <h1>Ranking</h1>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>User ID</th>
        <th>Quiz ID</th>
        <th>Points</th>
      </tr>
    </thead>
    <tbody>
      {% for result in ranking %}
        <tr>
          <td>{{ result.user.username }}</td>
          <td>{{ result.quiz.id }}</td>
          <td>{{ result.points }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

quizzes/templates/take_quiz.html
{% extends 'flask_user_layout.html' %}

{% block content %}
  <h1>Quiz {{ difficulty }}</h1>
  <form method="POST" action="">
    {% for field in form %}
      <div>
        {{ field.label }}:
        {% if field.errors %}
          <ul class="errors">{% for error in field.errors %}<li>{{ error }}</li>{% endfor %}</ul>
        {% endif %}
        {{ field }}
      </div>
    {% endfor %}
    <div>
      <button type="submit">Submit</button>
    </div>
  </form>
{% endblock %}